### ISSUE TITLE
NCCL ERROR

### ISSUE THREAD

**Issue by Bowen-sdu** [MarSaKi/ETPNav#16]
I can run the program normally when using a single GPU, but when I use two GPUs, I encounter the following error. Have you come across this issue before, and how should I resolve it?

```

Traceback (most recent call last):
  File "run.py", line 122, in <module>
    main()
  File "run.py", line 49, in main
Traceback (most recent call last):
  File "run.py", line 122, in <module>
    run_exp(**vars(args))
  File "run.py", line 107, in run_exp
    trainer.train()
  File "/home/huangbw/navigation/ETPNav/vlnce_baselines/ss_trainer_ETP.py", line 461, in train
    action_space=action_space,
  File "/home/huangbw/navigation/ETPNav/vlnce_baselines/ss_trainer_ETP.py", line 217, in _initialize_policy
    output_device=self.device, find_unused_parameters=False, broadcast_buffers=False)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 578, in __init__
    main()
  File "run.py", line 49, in main
    run_exp(**vars(args))
    dist._verify_model_across_ranks(self.process_group, parameters)
  File "run.py", line 107, in run_exp
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180593867/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, invalid usage, NCCL version 21.0.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
    trainer.train()
  File "/home/huangbw/navigation/ETPNav/vlnce_baselines/ss_trainer_ETP.py", line 461, in train
    action_space=action_space,
  File "/home/huangbw/navigation/ETPNav/vlnce_baselines/ss_trainer_ETP.py", line 217, in _initialize_policy
    output_device=self.device, find_unused_parameters=False, broadcast_buffers=False)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 578, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180593867/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, invalid usage, NCCL version 21.0.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
Exception ignored in: <bound method VectorEnv.__del__ of <habitat.core.vector_env.VectorEnv object at 0x7f0cd5b872e8>>
Traceback (most recent call last):
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/core/vector_env.py", line 588, in __del__
    self.close()
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/core/vector_env.py", line 459, in close
    write_fn((CLOSE_COMMAND, None))
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/core/vector_env.py", line 118, in __call__
    self.write_fn(data)
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 63, in send
    self.send_bytes(buf.getvalue())
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <bound method VectorEnv.__del__ of <habitat.core.vector_env.VectorEnv object at 0x7f0e603c9278>>
Traceback (most recent call last):
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/core/vector_env.py", line 588, in __del__
    self.close()
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/core/vector_env.py", line 459, in close
    write_fn((CLOSE_COMMAND, None))
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/core/vector_env.py", line 118, in __call__
    self.write_fn(data)
  File "/home/huangbw/navigation/ETPNav/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 63, in send
    self.send_bytes(buf.getvalue())
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2822127) of binary: /home/huangbw/miniconda3/envs/python36/bin/python
Traceback (most recent call last):
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/huangbw/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
run.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-12-10_17:04:32
  host      : iic
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2822128)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-10_17:04:32
  host      : iic
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2822127)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

```

**Comment by MarSaKi** [comment]
Hi, 
I didn't encounter this error before, it looks like maybe the pytorch version is not aligned.
Alternatively, I think you can change to other backends to have a quick inspection, such as:
`dist.init_process_group(backend='gloo', init_method='env://')`

**Comment by zhangyu0110** [comment]
I have the same question, may I ask how you resolved it later on?
